// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

var Is_absolute_url = require("is-absolute-url");

var absolute_url = Is_absolute_url("http://facebook.com");

var relative_url = "/photos";

exports.absolute_url = absolute_url;
exports.relative_url = relative_url;
/* absolute_url Not a pure module */
